package com.java.entity;// default package
// Generated 11 Feb, 2021 7:51:03 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Stock generated by hbm2java
 * 
 */
@Entity
@Table(name = "stock", catalog = "medical_stock")
public class Stock implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private int quantity;
	private int prize;
	private int total;

	public Stock() {
	}

	public Stock(String name, String description, int quantity, int prize, int total) {
		this.name = name;
		this.description = description;
		this.quantity = quantity;
		this.prize = prize;
		this.total = total;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@Column(name = "Quantity")
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	@Column(name = "Prize")
	public int getPrize() {
		return this.prize;
	}

	public void setPrize(int prize) {
		this.prize = prize;
	}
	@Column(name = "Total")
	public int getTotal() {
		return this.total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

}
